### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by cowbra** [Spikharpax/SARAHV5-Demo#1]
bonsoir, j'ai installé sarah v5 hier soir et j'ai rencontré un petit problème :
je ne comprends pas ce qu'il faut faire à cette étape : "Ajoutez test 1 pour une phrase "SARAH dis 
bonjour":" pouvez vous m'aider svp ?
cordialement hugo

**Comment by Spikharpax** [comment]
Bjr cowbra,

C'est un test de la brique switch 2 lignes au dessus.
Ce switch sert à différencier les phrases prononcées. Dans ce test 1, c’est pour une phrase "SARAH dis bonjour". Ce qu'il faut mettre dans ce test est défini juste en dessous.
Les autres tests plus bas sont pour les autres phrases, comme expliqué dans le Readme
